hydra:
  run:
    dir: ./

train:
    batch_size: 16
    lr: 1e-3
    pt_lr: 1e-4
    max_epoch: 20
    eval_epoch: 0
    seed: 0
    weight_decay: 1e-8
    lam1: 0.5
    lam2: 0.5

eval:
    batch_size: 16
    eval_max_len: 40
    eval_min_len: 10
    top_k: 30
    top_p: 0.9
    num_beams: 1
    temperature: 0.7
    repetition_penalty: 1.03
    no_repeat_ngram_size: 3
dataset:
    max_len: 256
model:
    max_dic: 512
    proj1: 256
    proj2: 32
debug: false
name: "exp_test"

